FROM openjdk:12-jdk-oracle
MAINTAINER MrBird 852252810@qq.com

COPY febs-auth-1.0-SNAPSHOT.jar /febs/febs-auth-1.0-SNAPSHOT.jar
ENTRYPOINT ["java", "-Xmx256m", "-jar", "/febs/febs-auth-1.0-SNAPSHOT.jar"]
