version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: febs-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    volumes:
      - /Users/jason/febs/mysql/data:/var/lib/mysql #挂载 MySQL数据
  redis:
    image: redis:latest
    container_name: febs-redis
    command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
    volumes:
      - /Users/jason/febs/redis/data:/data #挂载 Redis数据
      - /Users/jason/febs/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf #挂载 Redis配置
    ports:
      - 6379:6379
  rabbitmq:
    image: rabbitmq:3.8.3-management
    container_name: febs-rabbitmq
    volumes:
      - /Users/jason/febs/rabbitmq/data:/var/lib/rabbitmq #挂载 RabbitMQ数据
      - /Users/jason/febs/rabbitmq/log:/var/log/rabbitmq #挂载 RabbitMQ日志
    ports:
      - 5672:5672
      - 15672:15672

  nacos:
    image: nacos/nacos-server:latest
    container_name: febs-nacos
    env_file:
      - ./env/nacos-standlone-mysql.env
    volumes:
      - ./plugins/mysql/:/home/nacos/plugins/mysql/
      - ./logs/:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - 8001:8001
      - 9555:9555
    depends_on:
      - mysql
    links:
      - mysql:mysql-url
    restart: on-failure
